# -*- coding: utf-8 -*-
"""hotel data pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UJjJxni-xjpmVVVmSUbkPXpTns3xnnk

TASKS PERFORMED ON HOTEL BOOKING DATA
"""

import pandas as pd

hotels= pd.read_csv("hotel_booking_data.csv")

hotels.head()

df=pd.DataFrame(hotels)

df

"""TASK: How many rows are there?"""

hotels.info()

len(hotels)

"""TASK: Is there any missing data? If so, which column has the most missing data?"""

df.isnull()

hotels.isnull()

df.isnull().sum()

print(f"Yes, missing data, company column missing : {df['company'].isnull().sum()}")

"""TASK: Drop the "company" column from the dataset."""

df=df.drop('company',axis=1)



df

"""TASK: What are the top 5 most common country codes in the dataset?"""

df['country'].value_counts()

df['country'].value_counts()[:5]

"""TASK: What is the name of the person who paid the highest ADR (average daily rate)? How much was their ADR?"""

df['adr'].max()

df.sort_values('adr',ascending=False)[['adr','name']].iloc[0]

"""TASK: The adr is the average daily rate for a person's stay at the hotel. What is the mean adr across all the hotel stays in the dataset?"""

df['adr'].mean()

"""TASK: What is the average (mean) number of nights for a stay across the entire data set? Feel free to round this to 2 decimal points."""

df['total_staydays']=df['stays_in_week_nights']+ df['stays_in_weekend_nights']

round(df['total_staydays'].mean(),2)

"""TASK: What is the average total cost for a stay in the dataset? Not average daily cost, but total stay cost. (You will need to calculate total cost your self by using ADR and week day and weeknight stays). Feel free to round this to 2 decimal points."""

df['total_paid']=df['adr']*df['total_staydays']

round(df['total_paid'].mean(),2)

"""TASK: What are the names and emails of people who made exactly 5 "Special Requests"?"""

df[df['total_of_special_requests']==5][['name','email']]

"""TASK: What percentage of hotel stays were classified as "repeat guests"? (Do not base this off the name of the person, but instead of the is_repeated_guest column)"""

df['is_repeated_guest'].sum()

100*(df['is_repeated_guest'].sum()/len(hotels))

"""TASK: What are the top 5 most common last name in the dataset? Bonus: Can you figure this out in one line of pandas code? (For simplicity treat the a title such as MD as a last name, for example Caroline Conley MD can be said to have the last name MD)"""

df['name'].apply(lambda name: name.split()[1]).value_counts()[:5]

"""TASK: What are the names of the people who had booked the most number children and babies for their stay? (Don't worry if they canceled, only consider number of people reported at the time of their reservation)"""

df['children'].count()

df['babies'].count()

df['total_children']=df['children']+ df['babies']
df.sort_values('total_children',ascending=False)[['name','adults','total_children','babies','children']]

df.sort_values('total_children',ascending=False)[['name','adults','total_children','babies','children']][:5]

"""TASK: What are the top 3 most common area code in the phone numbers? (Area code is first 3 digits)"""

df['phone-number'].apply(lambda phone_number:phone_number.split('-')[0]).value_counts()[:3]

"""TASK: How many arrivals took place between the 1st and the 15th of the month (inclusive of 1 and 15) ?"""

df['arrival_date_day_of_month'].apply(lambda days:days in range(1,16)).sum()

"""Create a table for counts for each day of the week that people arrived. (E.g. 5000 arrivals were on a Monday, 3000 were on a Tuesday, etc..)"""

import numpy as np

def convert(day,month,year):
    return f'{day}-{month}-{year}'

df['date']=np.vectorize(convert)(df['arrival_date_day_of_month'],df['arrival_date_month'],df['arrival_date_year'])

df['date']=pd.to_datetime(df['date'])

df['date'].dt.day_name().value_counts()

